/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";
import { type Json } from "./../types/database.types";

export const ApplicationStatusSchema = z.union([
  z.literal("applied"),
  z.literal("pending_info"),
  z.literal("rejected"),
  z.literal("approved"),
]);

export const BookingStatusSchema = z.union([
  z.literal("pending"),
  z.literal("confirmed"),
  z.literal("cancelled"),
  z.literal("completed"),
]);

export const DayOfWeekSchema = z.union([
  z.literal("monday"),
  z.literal("tuesday"),
  z.literal("wednesday"),
  z.literal("thursday"),
  z.literal("friday"),
  z.literal("saturday"),
  z.literal("sunday"),
]);

export const MediaTypeSchema = z.union([
  z.literal("avatar"),
  z.literal("service_image"),
  z.literal("review_image"),
  z.literal("chat_image"),
  z.literal("application_image"),
  z.literal("landing_asset"),
  z.literal("logo_asset"),
  z.literal("other"),
]);

export const UserRoleSchema = z.union([
  z.literal("customer"),
  z.literal("stylist"),
  z.literal("admin"),
]);

export const jsonSchema: z.ZodSchema<Json> = z.lazy(() =>
  z
    .union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.union([jsonSchema, z.undefined()])),
      z.array(jsonSchema),
    ])
    .nullable(),
);

export const addressesRowSchema = z.object({
  city: z.string(),
  country: z.string(),
  created_at: z.string(),
  entry_instructions: z.string().nullable(),
  id: z.string(),
  is_primary: z.boolean(),
  latitude: z.number().nullable(),
  longitude: z.number().nullable(),
  nickname: z.string().nullable(),
  postal_code: z.string(),
  street_address: z.string(),
  updated_at: z.string(),
  user_id: z.string(),
});

export const addressesInsertSchema = z.object({
  city: z.string(),
  country: z.string(),
  created_at: z.string().optional(),
  entry_instructions: z.string().optional().nullable(),
  id: z.string().optional(),
  is_primary: z.boolean().optional(),
  latitude: z.number().optional().nullable(),
  longitude: z.number().optional().nullable(),
  nickname: z.string().optional().nullable(),
  postal_code: z.string(),
  street_address: z.string(),
  updated_at: z.string().optional(),
  user_id: z.string(),
});

export const addressesUpdateSchema = z.object({
  city: z.string().optional(),
  country: z.string().optional(),
  created_at: z.string().optional(),
  entry_instructions: z.string().optional().nullable(),
  id: z.string().optional(),
  is_primary: z.boolean().optional(),
  latitude: z.number().optional().nullable(),
  longitude: z.number().optional().nullable(),
  nickname: z.string().optional().nullable(),
  postal_code: z.string().optional(),
  street_address: z.string().optional(),
  updated_at: z.string().optional(),
  user_id: z.string().optional(),
});

export const addressesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("addresses_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const applicationCategoriesRowSchema = z.object({
  application_id: z.string(),
  category_id: z.string(),
});

export const applicationCategoriesInsertSchema = z.object({
  application_id: z.string(),
  category_id: z.string(),
});

export const applicationCategoriesUpdateSchema = z.object({
  application_id: z.string().optional(),
  category_id: z.string().optional(),
});

export const applicationCategoriesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("application_categories_application_id_fkey"),
    columns: z.tuple([z.literal("application_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("applications"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("application_categories_category_id_fkey"),
    columns: z.tuple([z.literal("category_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("service_categories"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const applicationsRowSchema = z.object({
  address_nickname: z.string().nullable(),
  birth_date: z.string(),
  city: z.string(),
  country: z.string(),
  created_at: z.string(),
  email: z.string(),
  entry_instructions: z.string().nullable(),
  full_name: z.string(),
  id: z.string(),
  phone_number: z.string(),
  postal_code: z.string(),
  price_range_currency: z.string(),
  price_range_from: z.number(),
  price_range_to: z.number(),
  professional_experience: z.string(),
  status: ApplicationStatusSchema,
  street_address: z.string(),
  user_id: z.string().nullable(),
});

export const applicationsInsertSchema = z.object({
  address_nickname: z.string().optional().nullable(),
  birth_date: z.string(),
  city: z.string(),
  country: z.string(),
  created_at: z.string().optional(),
  email: z.string(),
  entry_instructions: z.string().optional().nullable(),
  full_name: z.string(),
  id: z.string().optional(),
  phone_number: z.string(),
  postal_code: z.string(),
  price_range_currency: z.string().optional(),
  price_range_from: z.number(),
  price_range_to: z.number(),
  professional_experience: z.string(),
  status: ApplicationStatusSchema.optional(),
  street_address: z.string(),
  user_id: z.string().optional().nullable(),
});

export const applicationsUpdateSchema = z.object({
  address_nickname: z.string().optional().nullable(),
  birth_date: z.string().optional(),
  city: z.string().optional(),
  country: z.string().optional(),
  created_at: z.string().optional(),
  email: z.string().optional(),
  entry_instructions: z.string().optional().nullable(),
  full_name: z.string().optional(),
  id: z.string().optional(),
  phone_number: z.string().optional(),
  postal_code: z.string().optional(),
  price_range_currency: z.string().optional(),
  price_range_from: z.number().optional(),
  price_range_to: z.number().optional(),
  professional_experience: z.string().optional(),
  status: ApplicationStatusSchema.optional(),
  street_address: z.string().optional(),
  user_id: z.string().optional().nullable(),
});

export const applicationsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("applications_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const bookingServicesRowSchema = z.object({
  booking_id: z.string(),
  service_id: z.string(),
});

export const bookingServicesInsertSchema = z.object({
  booking_id: z.string(),
  service_id: z.string(),
});

export const bookingServicesUpdateSchema = z.object({
  booking_id: z.string().optional(),
  service_id: z.string().optional(),
});

export const bookingServicesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("booking_services_booking_id_fkey"),
    columns: z.tuple([z.literal("booking_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("bookings"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("booking_services_service_id_fkey"),
    columns: z.tuple([z.literal("service_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("services"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const bookingsRowSchema = z.object({
  address_id: z.string().nullable(),
  created_at: z.string(),
  customer_id: z.string(),
  end_time: z.string(),
  id: z.string(),
  message_to_stylist: z.string().nullable(),
  start_time: z.string(),
  status: BookingStatusSchema,
  stripe_payment_intent_id: z.string().nullable(),
  stylist_id: z.string(),
  total_duration_minutes: z.number(),
  total_price: z.number(),
  updated_at: z.string(),
});

export const bookingsInsertSchema = z.object({
  address_id: z.string().optional().nullable(),
  created_at: z.string().optional(),
  customer_id: z.string(),
  end_time: z.string(),
  id: z.string().optional(),
  message_to_stylist: z.string().optional().nullable(),
  start_time: z.string(),
  status: BookingStatusSchema.optional(),
  stripe_payment_intent_id: z.string().optional().nullable(),
  stylist_id: z.string(),
  total_duration_minutes: z.number(),
  total_price: z.number(),
  updated_at: z.string().optional(),
});

export const bookingsUpdateSchema = z.object({
  address_id: z.string().optional().nullable(),
  created_at: z.string().optional(),
  customer_id: z.string().optional(),
  end_time: z.string().optional(),
  id: z.string().optional(),
  message_to_stylist: z.string().optional().nullable(),
  start_time: z.string().optional(),
  status: BookingStatusSchema.optional(),
  stripe_payment_intent_id: z.string().optional().nullable(),
  stylist_id: z.string().optional(),
  total_duration_minutes: z.number().optional(),
  total_price: z.number().optional(),
  updated_at: z.string().optional(),
});

export const bookingsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("bookings_address_id_fkey"),
    columns: z.tuple([z.literal("address_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("addresses"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("bookings_customer_id_fkey"),
    columns: z.tuple([z.literal("customer_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("bookings_stylist_id_fkey"),
    columns: z.tuple([z.literal("stylist_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const chatMessagesRowSchema = z.object({
  chat_id: z.string(),
  content: z.string(),
  created_at: z.string(),
  id: z.string(),
  is_read: z.boolean(),
  sender_id: z.string(),
});

export const chatMessagesInsertSchema = z.object({
  chat_id: z.string(),
  content: z.string(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  is_read: z.boolean().optional(),
  sender_id: z.string(),
});

export const chatMessagesUpdateSchema = z.object({
  chat_id: z.string().optional(),
  content: z.string().optional(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  is_read: z.boolean().optional(),
  sender_id: z.string().optional(),
});

export const chatMessagesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("chat_messages_chat_id_fkey"),
    columns: z.tuple([z.literal("chat_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("chats"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("chat_messages_sender_id_fkey"),
    columns: z.tuple([z.literal("sender_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const chatsRowSchema = z.object({
  booking_id: z.string(),
  created_at: z.string(),
  id: z.string(),
  updated_at: z.string(),
});

export const chatsInsertSchema = z.object({
  booking_id: z.string(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  updated_at: z.string().optional(),
});

export const chatsUpdateSchema = z.object({
  booking_id: z.string().optional(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  updated_at: z.string().optional(),
});

export const chatsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("chats_booking_id_fkey"),
    columns: z.tuple([z.literal("booking_id")]),
    isOneToOne: z.literal(true),
    referencedRelation: z.literal("bookings"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const mediaRowSchema = z.object({
  application_id: z.string().nullable(),
  chat_message_id: z.string().nullable(),
  created_at: z.string(),
  file_path: z.string(),
  id: z.string(),
  media_type: MediaTypeSchema,
  owner_id: z.string().nullable(),
  review_id: z.string().nullable(),
  service_id: z.string().nullable(),
});

export const mediaInsertSchema = z.object({
  application_id: z.string().optional().nullable(),
  chat_message_id: z.string().optional().nullable(),
  created_at: z.string().optional(),
  file_path: z.string(),
  id: z.string().optional(),
  media_type: MediaTypeSchema,
  owner_id: z.string().optional().nullable(),
  review_id: z.string().optional().nullable(),
  service_id: z.string().optional().nullable(),
});

export const mediaUpdateSchema = z.object({
  application_id: z.string().optional().nullable(),
  chat_message_id: z.string().optional().nullable(),
  created_at: z.string().optional(),
  file_path: z.string().optional(),
  id: z.string().optional(),
  media_type: MediaTypeSchema.optional(),
  owner_id: z.string().optional().nullable(),
  review_id: z.string().optional().nullable(),
  service_id: z.string().optional().nullable(),
});

export const mediaRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("media_application_id_fkey"),
    columns: z.tuple([z.literal("application_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("applications"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("media_chat_message_id_fkey"),
    columns: z.tuple([z.literal("chat_message_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("chat_messages"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("media_owner_id_fkey"),
    columns: z.tuple([z.literal("owner_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("media_review_id_fkey"),
    columns: z.tuple([z.literal("review_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("reviews"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("media_service_id_fkey"),
    columns: z.tuple([z.literal("service_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("services"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const profilesRowSchema = z.object({
  bankid_verified: z.boolean(),
  created_at: z.string(),
  email: z.string().nullable(),
  full_name: z.string().nullable(),
  id: z.string(),
  phone_number: z.string().nullable(),
  role: UserRoleSchema,
  stripe_customer_id: z.string().nullable(),
  subscribed_to_newsletter: z.boolean(),
  updated_at: z.string(),
});

export const profilesInsertSchema = z.object({
  bankid_verified: z.boolean().optional(),
  created_at: z.string().optional(),
  email: z.string().optional().nullable(),
  full_name: z.string().optional().nullable(),
  id: z.string(),
  phone_number: z.string().optional().nullable(),
  role: UserRoleSchema.optional(),
  stripe_customer_id: z.string().optional().nullable(),
  subscribed_to_newsletter: z.boolean().optional(),
  updated_at: z.string().optional(),
});

export const profilesUpdateSchema = z.object({
  bankid_verified: z.boolean().optional(),
  created_at: z.string().optional(),
  email: z.string().optional().nullable(),
  full_name: z.string().optional().nullable(),
  id: z.string().optional(),
  phone_number: z.string().optional().nullable(),
  role: UserRoleSchema.optional(),
  stripe_customer_id: z.string().optional().nullable(),
  subscribed_to_newsletter: z.boolean().optional(),
  updated_at: z.string().optional(),
});

export const recurringUnavailabilityExceptionsRowSchema = z.object({
  id: z.string(),
  new_end_time: z.string().nullable(),
  new_start_time: z.string().nullable(),
  original_start_time: z.string(),
  series_id: z.string(),
});

export const recurringUnavailabilityExceptionsInsertSchema = z.object({
  id: z.string().optional(),
  new_end_time: z.string().optional().nullable(),
  new_start_time: z.string().optional().nullable(),
  original_start_time: z.string(),
  series_id: z.string(),
});

export const recurringUnavailabilityExceptionsUpdateSchema = z.object({
  id: z.string().optional(),
  new_end_time: z.string().optional().nullable(),
  new_start_time: z.string().optional().nullable(),
  original_start_time: z.string().optional(),
  series_id: z.string().optional(),
});

export const recurringUnavailabilityExceptionsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal(
      "recurring_unavailability_exceptions_series_id_fkey",
    ),
    columns: z.tuple([z.literal("series_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("stylist_recurring_unavailability"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const reviewsRowSchema = z.object({
  booking_id: z.string(),
  comment: z.string().nullable(),
  created_at: z.string(),
  customer_id: z.string(),
  id: z.string(),
  rating: z.number(),
  stylist_id: z.string(),
});

export const reviewsInsertSchema = z.object({
  booking_id: z.string(),
  comment: z.string().optional().nullable(),
  created_at: z.string().optional(),
  customer_id: z.string(),
  id: z.string().optional(),
  rating: z.number(),
  stylist_id: z.string(),
});

export const reviewsUpdateSchema = z.object({
  booking_id: z.string().optional(),
  comment: z.string().optional().nullable(),
  created_at: z.string().optional(),
  customer_id: z.string().optional(),
  id: z.string().optional(),
  rating: z.number().optional(),
  stylist_id: z.string().optional(),
});

export const reviewsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("reviews_booking_id_fkey"),
    columns: z.tuple([z.literal("booking_id")]),
    isOneToOne: z.literal(true),
    referencedRelation: z.literal("bookings"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("reviews_customer_id_fkey"),
    columns: z.tuple([z.literal("customer_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("reviews_stylist_id_fkey"),
    columns: z.tuple([z.literal("stylist_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const serviceCategoriesRowSchema = z.object({
  description: z.string().nullable(),
  id: z.string(),
  name: z.string(),
  parent_category_id: z.string().nullable(),
});

export const serviceCategoriesInsertSchema = z.object({
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  name: z.string(),
  parent_category_id: z.string().optional().nullable(),
});

export const serviceCategoriesUpdateSchema = z.object({
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  name: z.string().optional(),
  parent_category_id: z.string().optional().nullable(),
});

export const serviceCategoriesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("service_categories_parent_category_id_fkey"),
    columns: z.tuple([z.literal("parent_category_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("service_categories"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const serviceServiceCategoriesRowSchema = z.object({
  category_id: z.string(),
  service_id: z.string(),
});

export const serviceServiceCategoriesInsertSchema = z.object({
  category_id: z.string(),
  service_id: z.string(),
});

export const serviceServiceCategoriesUpdateSchema = z.object({
  category_id: z.string().optional(),
  service_id: z.string().optional(),
});

export const serviceServiceCategoriesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("service_service_categories_category_id_fkey"),
    columns: z.tuple([z.literal("category_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("service_categories"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("service_service_categories_service_id_fkey"),
    columns: z.tuple([z.literal("service_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("services"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const servicesRowSchema = z.object({
  at_customer_place: z.boolean(),
  at_stylist_place: z.boolean(),
  created_at: z.string(),
  description: z.string().nullable(),
  duration_minutes: z.number(),
  id: z.string(),
  price: z.number(),
  stylist_id: z.string(),
  title: z.string(),
  updated_at: z.string(),
});

export const servicesInsertSchema = z.object({
  at_customer_place: z.boolean().optional(),
  at_stylist_place: z.boolean().optional(),
  created_at: z.string().optional(),
  description: z.string().optional().nullable(),
  duration_minutes: z.number(),
  id: z.string().optional(),
  price: z.number(),
  stylist_id: z.string(),
  title: z.string(),
  updated_at: z.string().optional(),
});

export const servicesUpdateSchema = z.object({
  at_customer_place: z.boolean().optional(),
  at_stylist_place: z.boolean().optional(),
  created_at: z.string().optional(),
  description: z.string().optional().nullable(),
  duration_minutes: z.number().optional(),
  id: z.string().optional(),
  price: z.number().optional(),
  stylist_id: z.string().optional(),
  title: z.string().optional(),
  updated_at: z.string().optional(),
});

export const servicesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("services_stylist_id_fkey"),
    columns: z.tuple([z.literal("stylist_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const stylistAvailabilityRulesRowSchema = z.object({
  day_of_week: DayOfWeekSchema,
  end_time: z.string(),
  id: z.string(),
  start_time: z.string(),
  stylist_id: z.string(),
});

export const stylistAvailabilityRulesInsertSchema = z.object({
  day_of_week: DayOfWeekSchema,
  end_time: z.string(),
  id: z.string().optional(),
  start_time: z.string(),
  stylist_id: z.string(),
});

export const stylistAvailabilityRulesUpdateSchema = z.object({
  day_of_week: DayOfWeekSchema.optional(),
  end_time: z.string().optional(),
  id: z.string().optional(),
  start_time: z.string().optional(),
  stylist_id: z.string().optional(),
});

export const stylistAvailabilityRulesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("stylist_availability_rules_stylist_id_fkey"),
    columns: z.tuple([z.literal("stylist_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const stylistRecurringUnavailabilityRowSchema = z.object({
  end_time: z.string(),
  id: z.string(),
  rrule: z.string(),
  series_end_date: z.string().nullable(),
  series_start_date: z.string(),
  start_time: z.string(),
  stylist_id: z.string(),
  title: z.string().nullable(),
});

export const stylistRecurringUnavailabilityInsertSchema = z.object({
  end_time: z.string(),
  id: z.string().optional(),
  rrule: z.string(),
  series_end_date: z.string().optional().nullable(),
  series_start_date: z.string(),
  start_time: z.string(),
  stylist_id: z.string(),
  title: z.string().optional().nullable(),
});

export const stylistRecurringUnavailabilityUpdateSchema = z.object({
  end_time: z.string().optional(),
  id: z.string().optional(),
  rrule: z.string().optional(),
  series_end_date: z.string().optional().nullable(),
  series_start_date: z.string().optional(),
  start_time: z.string().optional(),
  stylist_id: z.string().optional(),
  title: z.string().optional().nullable(),
});

export const stylistRecurringUnavailabilityRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal(
      "stylist_recurring_unavailability_stylist_id_fkey",
    ),
    columns: z.tuple([z.literal("stylist_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const stylistUnavailabilityRowSchema = z.object({
  end_time: z.string(),
  id: z.string(),
  reason: z.string().nullable(),
  start_time: z.string(),
  stylist_id: z.string(),
});

export const stylistUnavailabilityInsertSchema = z.object({
  end_time: z.string(),
  id: z.string().optional(),
  reason: z.string().optional().nullable(),
  start_time: z.string(),
  stylist_id: z.string(),
});

export const stylistUnavailabilityUpdateSchema = z.object({
  end_time: z.string().optional(),
  id: z.string().optional(),
  reason: z.string().optional().nullable(),
  start_time: z.string().optional(),
  stylist_id: z.string().optional(),
});

export const stylistUnavailabilityRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("stylist_unavailability_stylist_id_fkey"),
    columns: z.tuple([z.literal("stylist_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const getMyRoleArgsSchema = z.object({});

export const getMyRoleReturnsSchema = UserRoleSchema;
