/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";
import * as generated from "./database.schema";
export type PublicApplicationStatus = z.infer<
  typeof generated.publicApplicationStatusSchema
>;
export type PublicBookingStatus = z.infer<
  typeof generated.publicBookingStatusSchema
>;
export type PublicDayOfWeek = z.infer<typeof generated.publicDayOfWeekSchema>;
export type PublicMediaType = z.infer<typeof generated.publicMediaTypeSchema>;
export type PublicUserRole = z.infer<typeof generated.publicUserRoleSchema>;
export type Json = z.infer<typeof generated.jsonSchema>;
export type PublicAddressesRow = z.infer<
  typeof generated.publicAddressesRowSchema
>;
export type PublicAddressesInsert = z.infer<
  typeof generated.publicAddressesInsertSchema
>;
export type PublicAddressesUpdate = z.infer<
  typeof generated.publicAddressesUpdateSchema
>;
export type PublicAddressesRelationships = z.infer<
  typeof generated.publicAddressesRelationshipsSchema
>;
export type PublicApplicationCategoriesRow = z.infer<
  typeof generated.publicApplicationCategoriesRowSchema
>;
export type PublicApplicationCategoriesInsert = z.infer<
  typeof generated.publicApplicationCategoriesInsertSchema
>;
export type PublicApplicationCategoriesUpdate = z.infer<
  typeof generated.publicApplicationCategoriesUpdateSchema
>;
export type PublicApplicationCategoriesRelationships = z.infer<
  typeof generated.publicApplicationCategoriesRelationshipsSchema
>;
export type PublicApplicationsRow = z.infer<
  typeof generated.publicApplicationsRowSchema
>;
export type PublicApplicationsInsert = z.infer<
  typeof generated.publicApplicationsInsertSchema
>;
export type PublicApplicationsUpdate = z.infer<
  typeof generated.publicApplicationsUpdateSchema
>;
export type PublicApplicationsRelationships = z.infer<
  typeof generated.publicApplicationsRelationshipsSchema
>;
export type PublicBookingServicesRow = z.infer<
  typeof generated.publicBookingServicesRowSchema
>;
export type PublicBookingServicesInsert = z.infer<
  typeof generated.publicBookingServicesInsertSchema
>;
export type PublicBookingServicesUpdate = z.infer<
  typeof generated.publicBookingServicesUpdateSchema
>;
export type PublicBookingServicesRelationships = z.infer<
  typeof generated.publicBookingServicesRelationshipsSchema
>;
export type PublicBookingsRow = z.infer<
  typeof generated.publicBookingsRowSchema
>;
export type PublicBookingsInsert = z.infer<
  typeof generated.publicBookingsInsertSchema
>;
export type PublicBookingsUpdate = z.infer<
  typeof generated.publicBookingsUpdateSchema
>;
export type PublicBookingsRelationships = z.infer<
  typeof generated.publicBookingsRelationshipsSchema
>;
export type PublicChatMessagesRow = z.infer<
  typeof generated.publicChatMessagesRowSchema
>;
export type PublicChatMessagesInsert = z.infer<
  typeof generated.publicChatMessagesInsertSchema
>;
export type PublicChatMessagesUpdate = z.infer<
  typeof generated.publicChatMessagesUpdateSchema
>;
export type PublicChatMessagesRelationships = z.infer<
  typeof generated.publicChatMessagesRelationshipsSchema
>;
export type PublicChatsRow = z.infer<typeof generated.publicChatsRowSchema>;
export type PublicChatsInsert = z.infer<
  typeof generated.publicChatsInsertSchema
>;
export type PublicChatsUpdate = z.infer<
  typeof generated.publicChatsUpdateSchema
>;
export type PublicChatsRelationships = z.infer<
  typeof generated.publicChatsRelationshipsSchema
>;
export type PublicMediaRow = z.infer<typeof generated.publicMediaRowSchema>;
export type PublicMediaInsert = z.infer<
  typeof generated.publicMediaInsertSchema
>;
export type PublicMediaUpdate = z.infer<
  typeof generated.publicMediaUpdateSchema
>;
export type PublicMediaRelationships = z.infer<
  typeof generated.publicMediaRelationshipsSchema
>;
export type PublicProfilesRow = z.infer<
  typeof generated.publicProfilesRowSchema
>;
export type PublicProfilesInsert = z.infer<
  typeof generated.publicProfilesInsertSchema
>;
export type PublicProfilesUpdate = z.infer<
  typeof generated.publicProfilesUpdateSchema
>;
export type PublicRecurringUnavailabilityExceptionsRow = z.infer<
  typeof generated.publicRecurringUnavailabilityExceptionsRowSchema
>;
export type PublicRecurringUnavailabilityExceptionsInsert = z.infer<
  typeof generated.publicRecurringUnavailabilityExceptionsInsertSchema
>;
export type PublicRecurringUnavailabilityExceptionsUpdate = z.infer<
  typeof generated.publicRecurringUnavailabilityExceptionsUpdateSchema
>;
export type PublicRecurringUnavailabilityExceptionsRelationships = z.infer<
  typeof generated.publicRecurringUnavailabilityExceptionsRelationshipsSchema
>;
export type PublicReviewsRow = z.infer<typeof generated.publicReviewsRowSchema>;
export type PublicReviewsInsert = z.infer<
  typeof generated.publicReviewsInsertSchema
>;
export type PublicReviewsUpdate = z.infer<
  typeof generated.publicReviewsUpdateSchema
>;
export type PublicReviewsRelationships = z.infer<
  typeof generated.publicReviewsRelationshipsSchema
>;
export type PublicServiceCategoriesRow = z.infer<
  typeof generated.publicServiceCategoriesRowSchema
>;
export type PublicServiceCategoriesInsert = z.infer<
  typeof generated.publicServiceCategoriesInsertSchema
>;
export type PublicServiceCategoriesUpdate = z.infer<
  typeof generated.publicServiceCategoriesUpdateSchema
>;
export type PublicServiceCategoriesRelationships = z.infer<
  typeof generated.publicServiceCategoriesRelationshipsSchema
>;
export type PublicServicesRow = z.infer<
  typeof generated.publicServicesRowSchema
>;
export type PublicServicesInsert = z.infer<
  typeof generated.publicServicesInsertSchema
>;
export type PublicServicesUpdate = z.infer<
  typeof generated.publicServicesUpdateSchema
>;
export type PublicServicesRelationships = z.infer<
  typeof generated.publicServicesRelationshipsSchema
>;
export type PublicStylistAvailabilityRulesRow = z.infer<
  typeof generated.publicStylistAvailabilityRulesRowSchema
>;
export type PublicStylistAvailabilityRulesInsert = z.infer<
  typeof generated.publicStylistAvailabilityRulesInsertSchema
>;
export type PublicStylistAvailabilityRulesUpdate = z.infer<
  typeof generated.publicStylistAvailabilityRulesUpdateSchema
>;
export type PublicStylistAvailabilityRulesRelationships = z.infer<
  typeof generated.publicStylistAvailabilityRulesRelationshipsSchema
>;
export type PublicStylistRecurringUnavailabilityRow = z.infer<
  typeof generated.publicStylistRecurringUnavailabilityRowSchema
>;
export type PublicStylistRecurringUnavailabilityInsert = z.infer<
  typeof generated.publicStylistRecurringUnavailabilityInsertSchema
>;
export type PublicStylistRecurringUnavailabilityUpdate = z.infer<
  typeof generated.publicStylistRecurringUnavailabilityUpdateSchema
>;
export type PublicStylistRecurringUnavailabilityRelationships = z.infer<
  typeof generated.publicStylistRecurringUnavailabilityRelationshipsSchema
>;
export type PublicStylistUnavailabilityRow = z.infer<
  typeof generated.publicStylistUnavailabilityRowSchema
>;
export type PublicStylistUnavailabilityInsert = z.infer<
  typeof generated.publicStylistUnavailabilityInsertSchema
>;
export type PublicStylistUnavailabilityUpdate = z.infer<
  typeof generated.publicStylistUnavailabilityUpdateSchema
>;
export type PublicStylistUnavailabilityRelationships = z.infer<
  typeof generated.publicStylistUnavailabilityRelationshipsSchema
>;
export type PublicGetMyRoleArgs = z.infer<
  typeof generated.publicGetMyRoleArgsSchema
>;
export type PublicGetMyRoleReturns = z.infer<
  typeof generated.publicGetMyRoleReturnsSchema
>;
